### ISSUE TITLE
feat: Ping support for WebSocket

### ISSUE THREAD

**Issue by alexander-hagen** [bennycode/coinbase-pro-node#374]
WebSocket times-out after 100 seconds from establishing connection and subscribing to channel. There is no ping implemented to keep the WebSocket alive. I have implemented a work-around by re-subscribing every minute, but would be great if the connection would stay open.

<pre><code>    account._client.ws.subscribe([
      { name: WebSocketChannelName.USER, product_ids: user._products }
    ]);</code></pre>

**Comment by bennycode** [comment]
Thanks for making me aware of this. My research shows that we should connect to the [heartbeat](https://github.com/coinbase/coinbase-pro-node/issues/200#issuecomment-355608373) channel and monitor the "beats". If there are not enough beats, we can assume that the channel timed out and do a reconnect.

**Comment by alexander-hagen** [comment]
Even with the heartbeat, the websocket will timeout after 100 secs. You then always need to reconnect after 100 secs. Monitoring heartbeat is not necessary to detect disconnects. I previously already did that by monitoring close events on the websocket, and then reconnect. The drawback of that is that my software then needs to reinitialize as any events between disconnect and reinitialization are lost.

ws module supports ping. It would already be helpful to know how to call this given the socket in WebSocketClient.socket. We could then extend WebSocketClient class, or I can solve it in my own code.

**Comment by bennycode** [comment]
I checked the [ws ping example](https://github.com/websockets/ws#how-to-detect-and-close-broken-connections) and all it does on the client-side is to listen for a `'ping'` message (heartbeat) from the server and to reconnect (by calling `terminate` first) if the `'ping'` message does not arrive in time. So that means we would have to check for Coinbase Pro heartbeats and if those don't arrive in time we call `reconnect` from the `socket` in `WebSocketClient.ts`.

**Comment by alexander-hagen** [comment]
The ws ping example uses setInterval() to send a ping message from client to Coinbase server at 30s intervals, and waits for a pong back from the Coinbase server.  I've tried <code>this._client.ws.socket.ping(noop)</code> but that that's not the correct path to the ping function.

This is different from the heartbeat channel, that works in opposite direction, from Coinbase server to our client. There is no need to monitor Coinbase heartbeat channel as <code>this._client.ws.on(WebSocketEvent.ON_CLOSE, callback)</code> will do the same.

**Comment by alexander-hagen** [comment]
I managed to send a ping from my client to Coinbase, and got a pong back. Let me try to propose a patch ;-)

**Comment by alexander-hagen** [comment]
I'm still struggling with the TypeScript. Here's the code in NodeJS that works for me. It needs 2 lines of code: the clearInterval() in the close event, and the setInterval in the open event. Can you have a look at correct syntax for TS?

<pre><code>this.socket.onclose = (event) => {
    clearInterval(this.pingint);
    this.emit(WebSocketEvent.ON_CLOSE, event);
};

...

this.socket.onopen = () => {
    this.emit(WebSocketEvent.ON_OPEN);
    this.pingint=setInterval( () => { this.socket._ws.ping( () => {}) } , 60000);
};</code></pre>

**Comment by bennycode** [comment]
Thanks for your submission. Inspired by your idea, I created a PR which implements sending pings BUT also listens for responding pongs. If a pong message doesn't arrive in time, the socket will automatically reconnect: https://github.com/bennycode/coinbase-pro-node/pull/377

This solution will be good enough for Node.js. If the library is used in web browsers, then there is no `ws` package because the native `WebSocket` API will be used. In this case the code does not have access to a `ping` method. If we want to support keeping the WebSocket alive in web browsers, then we must listen to Coinbase Pro's heartbeat channel and do a reconnect if messages don't arrive in time.

**Comment by bennycode** [comment]
Please test with v2.17.0.

**Comment by alexander-hagen** [comment]
This gives an error in NodeJS when it calls the heartbeat

<pre><code>
node:internal/validators:212
    throw new ERR_INVALID_CALLBACK(callback);
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at setTimeout (node:timers:135:3)
    at WebSocket.heartbeat (/home/pi/coinbasebot/node_modules/coinbase-pro-node/dist/client/WebSocketClient.js:263:28)
    at WebSocket.emit (node:events:376:20)
    at Receiver.receiverOnPong (/home/pi/coinbasebot/node_modules/coinbase-pro-node/node_modules/ws/lib/websocket.js:851:20)
    at Receiver.emit (node:events:376:20)
    at Receiver.controlMessage (/home/pi/coinbasebot/node_modules/coinbase-pro-node/node_modules/ws/lib/receiver.js:479:12)
    at Receiver.getData (/home/pi/coinbasebot/node_modules/coinbase-pro-node/node_modules/ws/lib/receiver.js:350:42)
    at Receiver.startLoop (/home/pi/coinbasebot/node_modules/coinbase-pro-node/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/home/pi/coinbasebot/node_modules/coinbase-pro-node/node_modules/ws/lib/receiver.js:78:10)
    at writeOrBuffer (node:internal/streams/writable:395:12) {
  code: 'ERR_INVALID_CALLBACK'
}
</code></pre>

**Comment by bennycode** [comment]
Ops, my bad! I fixed it with v2.17.1. 🍀

**Comment by alexander-hagen** [comment]
I now works. Thanks for fixing
