### ISSUE TITLE
Add automatic re-subscribe to channels upon connection drop

### ISSUE THREAD

**Issue by hjoelr** [bennycode/coinbase-pro-node#421]
@bennycode First off, thank you for a great library! It has gotten me a long way in my project.

As far as I can tell, if the WebSocket connection is dropped, the next time it is connected it is up to the code using the library to re-subscribe to the channels to which the dropped connection was subscribed. I've implemented the logic for this in my own code, but was wondering if the place for this should be in this library? I'd be willing to put together a PR at some point if you thought that would be a good fit.

So, essentially, when the code using the library calls `WebSocketClient.subscribe()`, the WebSocketClient would keep track of what channels have been requested to subscribe. If something like `WebSocketClient.disconnect()` was called, it would forget previous subscriptions. Otherwise, when the WebSocket comes back up, it would automatically re-subscribe to the channels that were subscribed before the WebSocket went down. No worries if you don't think that logic fits in the library.

**Comment by bennycode** [comment]
Hi @hjoelr, this sounds like a great idea. You can also add a parameter to the `disconnect` function which controls if previous subscriptions should be cleared or not. Like a `cleanUp` parameter. Might be beneficial for people who want to disconnect on purpose for some time (because they are offline, etc.) and then reconnect without the need to resubscribe to all channels manually.

**Comment by hjoelr** [comment]
@bennycode Okay, I'll see if I can put something together. It may be a week or two before I can submit something.

**Comment by bennycode** [comment]
Cool. Just take your time. I will close this issue and wait for your PR. 🙂
