### ISSUE TITLE
request timestamp expired

### ISSUE THREAD

**Issue by Allandy** [bennycode/coinbase-pro-node#497]
anyone know how to increase rec window for this?

**Comment by bennycode** [comment]
Hi @Allandy, are you receiving this error with every request or only on some special endpoints? Can you post some example code so that I can get an idea about what you are trying to do?

From the first glance, it looks like your connection to the Coinbase servers is not responding in time. In which timezone are you?

**Comment by Allandy** [comment]
It's intermittent . Perhaps when Coinbase severs are very busy?? My sever is in Singapore . What's the best course of action when this happens?

**Comment by bennycode** [comment]
When it happens sporadically then it's because a specific request took longer than expected. This can happen because of many reasons, i.e. busy Coinbase server's or slow connection between your server and Coinbase. 

The current timeout is set to [50000ms](https://github.com/bennycode/coinbase-pro-node/blob/v3.0.4/src/client/RESTClient.ts#L59-L62) which is already very long. You can increase that value by overriding `client.rest.defaults.timeout` as shown here: 

https://github.com/bennycode/coinbase-pro-node/blob/24a5f8e2de1f6960f73069138ff07345a0698c1a/src/client/RESTClient.test.ts#L20-L25

Do you have a chance to catch that error in your code and just retry the request if it fails? That would probably be the best solution.

**Comment by Allandy** [comment]
Ok will try catch and retry.cheers
