### ISSUE TITLE
wrong candlesticks data

### ISSUE THREAD

**Issue by albertotesoro** [bennycode/coinbase-pro-node#684]
I've been struggling with this all day: all candlesticks values are correct except the "close" value.
i can't figure out if it's a coinbase API issue with timeframe 1H (i'm not using sandbox) or an inconsistency of closing time for the candle in code

**Comment by hjoelr** [comment]
@albertotesoro Can you give a little more detail? Maybe share a code snippet that you're using and what you are comparing the "close" value to to determine that it's wrong.

Also, the "close" value of the last candle will not be accurate because the candle time frame hasn't actually closed. In this case, the "close" value is the last value the price was when you requested the candles.

**Comment by albertotesoro** [comment]
first of all thank you for reply;
and it's my misunderstanding because, as you said, the last candle isn't closed yet (but min/max are settled)... but since i'm GMT+1  i was considering candle[candle.length-1] timestamp the last completed one (while it has to be the length-2 one);
sorry for bothering and nice work guys

**Comment by hjoelr** [comment]
@albertotesoro You're welcome. Glad you could get that cleared up. If this issue is resolved, can you mark it as such?
