### ISSUE TITLE
Add ability to generate wallet addresses

### ISSUE THREAD

**Issue by jonluca** [bennycode/coinbase-pro-node#727]
The [official docs](https://docs.cloud.coinbase.com/exchange/reference/exchangerestapi_postcoinbaseaccountaddresses) have an endpoint to generate a deposit address for an account, by `POST`ing to:

```
https://api.exchange.coinbase.com/coinbase-accounts/{account_id}/addresses
```

I don't believe the library currently has this functionality, it would be nice to have added

**Comment by bennycode** [comment]
Hi @jonluca and thank you very much for your great contribution (#728). I merged your code and updated some URLs from "pro.coinbase.com" to "exchange.coinbase.com". I consider this URL update a breaking change which is why there is coinbase-pro-node v5.0.0 now. It includes the ability to generate wallet addresses. 🎉

**Comment by jonluca** [comment]
Nice! I agree re: breaking change. It's _probably_ safe but it's the kind of change that might be an issue for some using the package. Thanks for ther fast response and update!
